title: Medical Classification Challenge
description: 🏥 Sistema de IA para clasificación automática de literatura médica | F1-Score: 0.864
theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - DEPLOYMENT.md
  - LICENSE
markdown: kramdown
kramdown:
  parse_block_html: true
